# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jabit
email: chrigu.meyer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You want to create an awesome Bitmessage app using Jabit? Then you've come
  to the right place!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dissem.github.io/Jabit" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Dissem

# Build settings
markdown: kramdown
